# Generated by Django 6.0.6 on 2026-06-05 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("modules", "0001_initial"),
        ("quizzes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Progress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("progress_percentage", models.FloatField(default=0.0)),
                ("last_accessed", models.DateTimeField(auto_now=True)),
                (
                    "completed_modules",
                    models.ManyToManyField(
                        blank=True, related_name="completions", to="modules.module"
                    ),
                ),
                (
                    "completed_quizzes",
                    models.ManyToManyField(
                        blank=True, related_name="completions", to="quizzes.quiz"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Progress",
                "verbose_name_plural": "Progress Records",
            },
        ),
    ]
